In [1]:
import pandas as pd 
import numpy as np

In [2]:
movies=pd.read_csv(r"C:\Users\user\Desktop\movierecommendation\tmdb_5000_movies.csv")
credits=pd.read_csv(r"C:\Users\user\Desktop\movierecommendation\tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [8]:
movies.isna().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.isna().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
movie_id                0
cast                    0
crew                    0
dtype: int64

In [11]:
df=movies[['genres','keywords','overview','production_companies','cast','crew','movie_id','title']]

In [12]:
df.head(1)

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,Avatar

In [13]:
import ast

In [14]:
def convert(text):
    L=[]
    for i in ast.literal_eval(text):
        L.append(i['name'])
        
    return L

In [15]:
df['genres']=df['genres'].apply(convert)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\4149380980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(convert)

In [16]:
df.head()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,Avatar
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529,John Carter

In [17]:
df['keywords']=df['keywords'].apply(convert)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\234733079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(convert)

In [18]:
df['production_companies']=df['production_companies'].apply(convert)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\2758196337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['production_companies']=df['production_companies'].apply(convert)

In [19]:
df.head()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq, B24]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros., DC Entertai...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",[Walt Disney Pictures],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529,John Carter

In [20]:
df['cast']=df['cast'].apply(convert)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\769866844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast']=df['cast'].apply(convert)

In [21]:
df.head()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq, B24]","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros., DC Entertai...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529,John Carter

In [22]:
df['cast']=df['cast'].apply(lambda x:x[0:3])

C:\Users\user\AppData\Local\Temp\ipykernel_12120\1394110224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast']=df['cast'].apply(lambda x:x[0:3])

In [23]:
df

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq, B24]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros., DC Entertai...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529,John Carter
...,...,...,...,...,...,...,...,...
4779,[Comedy],"[salesclerk, loser, aftercreditsstinger]",Convenience and video store clerks Dante and R...,"[Miramax Films, View Askew Productions]","[Brian O'Halloran, Jeff Anderson, Jason Mewes]","[{""credit_id"": ""52fe434ac3a36847f8049253"", ""de...",2292,Clerks
4787,"[Comedy, Romance]","[dating, divorce, sex scene, sex comedy, anti ...",Sasha tries to get her soon-to-be ex husband K...,[],"[Suzi Lorraine, Jared Degado, Heather Dorff]","[{""credit_id"": ""52fe4ee39251416c911412e7"", ""de...",255266,Dry Spell
4797,[Horror],[home invasion],Recently dumped by his girlfirend for another ...,"[Park Films, Camera Stylo Films]","[Michael Parle, Emma Eliza Regan, Patrick O'Do...","[{""credit_id"": ""54c7851b925141679100372a"", ""de...",157185,Tin Can Man
4802,"[Science Fiction, Drama, Thriller]","[distrust, garage, identity crisis, time trave...",Friends/fledgling entrepreneurs invent a devic...,[Thinkfilm],"[Shane Carruth, David Sullivan, Casey Gooden]","[{""credit_id"": ""52fe45e79251416c75066791"", ""de...",14337,Primer
4807,[],[],When ambitious New York attorney Sam is sent t...,[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",126186,Shanghai Calling

In [24]:
def get_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [25]:
df['crew']=df['crew'].apply(get_director)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\1977471344.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew']=df['crew'].apply(get_director)

In [26]:
def change(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1494 entries, 0 to 4807
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   genres                1494 non-null   object
 1   keywords              1494 non-null   object
 2   overview              1494 non-null   object
 3   production_companies  1494 non-null   object
 4   cast                  1494 non-null   object
 5   crew                  1494 non-null   object
 6   movie_id              1494 non-null   int64
 7   title                 1494 non-null   object
dtypes: int64(1), object(7)
memory usage: 105.0+ KB

In [28]:
df['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [29]:
df['cast']=df['cast'].apply(change)
df['genres']=df['genres'].apply(change)
df['crew']=df['crew'].apply(change)
df['keywords']=df['keywords'].apply(change)
df['production_companies']=df['production_companies'].apply(change)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\2858062329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast']=df['cast'].apply(change)
C:\Users\user\AppData\Local\Temp\ipykernel_12120\2858062329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(change)
C:\Users\user\AppData\Local\Temp\ipykernel_12120\2858062329.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew']=df['crew'].apply(change)
C:\Users\user\AppData\Local\Temp\ipykernel_12120\2858062329.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(change)
C:\Users\user\AppData\Local\Temp\ipykernel_12120\2858062329.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['production_companies']=df['production_companies'].apply(change)

In [30]:
df.head()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...","[WaltDisneyPictures, JerryBruckheimerFilms, Se...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bond’s past sends him o...,"[ColumbiaPictures, Danjaq, B24]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,"[LegendaryPictures, WarnerBros., DCEntertainme...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026,The Dark Knight Rises
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...",[WaltDisneyPictures],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529,John Carter

In [31]:
def split_text(x):
    if isinstance(x, str):
        return x.split()
    else:
        return []

In [32]:
df['overview']=df['overview'].apply(split_text)

C:\Users\user\AppData\Local\Temp\ipykernel_12120\39125544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview']=df['overview'].apply(split_text)

In [33]:
df.head()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995,Avatar
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[WaltDisneyPictures, JerryBruckheimerFilms, Se...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285,Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[ColumbiaPictures, Danjaq, B24]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647,Spectre
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[LegendaryPictures, WarnerBros., DCEntertainme...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026,The Dark Knight Rises
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",[WaltDisneyPictures],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529,John Carter

In [34]:
for i,j in enumerate(movies.overview):
    if(isinstance(j,str)):
        continue
    else:
        print(i)
        break

In [35]:
movies.iloc[2774:,2]

Series([], Name: homepage, dtype: object)

In [36]:
df.tail()

,genres,keywords,overview,production_companies,cast,crew,movie_id,title
4779,[Comedy],"[salesclerk, loser, aftercreditsstinger]","[Convenience, and, video, store, clerks, Dante...","[MiramaxFilms, ViewAskewProductions]","[BrianO'Halloran, JeffAnderson, JasonMewes]",[KevinSmith],2292,Clerks
4787,"[Comedy, Romance]","[dating, divorce, sexscene, sexcomedy, antirom...","[Sasha, tries, to, get, her, soon-to-be, ex, h...",[],"[SuziLorraine, JaredDegado, HeatherDorff]",[TravisLegge],255266,Dry Spell
4797,[Horror],[homeinvasion],"[Recently, dumped, by, his, girlfirend, for, a...","[ParkFilms, CameraStyloFilms]","[MichaelParle, EmmaElizaRegan, PatrickO'Donnell]",[IvanKavanagh],157185,Tin Can Man
4802,"[ScienceFiction, Drama, Thriller]","[distrust, garage, identitycrisis, timetravel,...","[Friends/fledgling, entrepreneurs, invent, a, ...",[Thinkfilm],"[ShaneCarruth, DavidSullivan, CaseyGooden]",[ShaneCarruth],14337,Primer
4807,[],[],"[When, ambitious, New, York, attorney, Sam, is...",[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],126186,Shanghai Calling

In [37]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']+df['production_companies']

C:\Users\user\AppData\Local\Temp\ipykernel_12120\1679419058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']+df['production_companies']

In [38]:
df.head(1)

,genres,keywords,overview,production_companies,cast,crew,movie_id,title,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [39]:
new=df.drop(columns=['genres','keywords','overview','production_companies','cast','crew',])

In [40]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
new['tags']=new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [43]:
vector=cv.fit_transform(new['tags']).toarray()

In [44]:
vector.shape

(1494, 5000)

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
similarity=cosine_similarity(vector)

In [47]:
similarity.shape

(1494, 1494)

In [48]:
similarity

array([[1.        , 0.07905694, 0.05345225, ..., 0.        , 0.05423261,
        0.02635231],
       [0.07905694, 1.        , 0.05634362, ..., 0.04303315, 0.        ,
        0.        ],
       [0.05345225, 0.05634362, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.04303315, 0.        , ..., 1.        , 0.        ,
        0.04303315],
       [0.05423261, 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.02635231, 0.        , 0.        , ..., 0.04303315, 0.        ,
        1.        ]])

In [49]:
new[new['title'] == 'The Lego Movie']

,movie_id,title,tags
744,137106,The Lego Movie,"An ordinary Lego mini-figure, mistakenly thoug..."

In [50]:
distances = sorted(list(enumerate(similarity[new[new['title'] == 'The Lego Movie'].index[0]])),reverse=True,key = lambda x: x[1])

In [51]:
distances

[(744, 0.9999999999999997),
 (1332, 0.2960782627318961),
 (1228, 0.27311549679956754),
 (1000, 0.25425669046549126),
 (901, 0.23618874648666505),
 (904, 0.21681454519599694),
 (1367, 0.20571764439712248),
 (955, 0.19696969696969693),
 (1384, 0.19462473604038075),
 (506, 0.19395245515057077),
 (1112, 0.18556740475630135),
 (657, 0.1796644508187709),
 (440, 0.1709408646894569),
 (330, 0.1705887719063863),
 (338, 0.16943474841747147),
 (134, 0.16894148755011248),
 (1473, 0.1664500757152958),
 (526, 0.16412198797244362),
 (876, 0.1618889317032706),
 (1269, 0.15990053726670783),
 (277, 0.15745916432444337),
 (1487, 0.15745916432444337),
 (1005, 0.15731330124142312),
 (1455, 0.15508070173307845),
 (1431, 0.15316791621349668),
 (400, 0.15075567228888184),
 (445, 0.149270358506633),
 (729, 0.149270358506633),
 (742, 0.149270358506633),
 (1397, 0.1484539238050411),
 (1357, 0.14712247158412492),
 (304, 0.14519080172812554),
 (740, 0.14309095175803563),
 (518, 0.14213381090374028),
 (1051, 0.14119562368122623),
 (1331, 0.13797289239745258),
 (1389, 0.13797289239745258),
 (947, 0.13714509626474833),
 (402, 0.1315903389919538),
 (1338, 0.1315903389919538),
 (962, 0.1313989347611986),
 (1353, 0.12989718332941094),
 (1223, 0.128564869306645),
 (1034, 0.12792042981336624),
 (1225, 0.12707606131310362),
 (1175, 0.12568317499614473),
 (1166, 0.1256297269074015),
 (760, 0.12309149097933272),
 (1343, 0.12309149097933272),
 (692, 0.12233863076108328),
 (707, 0.12214096331049185),
 (1315, 0.12185435916898847),
 (1299, 0.12141669877745292),
 (588, 0.11854779319316987),
 (1262, 0.11826247919781652),
 (1375, 0.11826247919781652),
 (682, 0.1172544117802414),
 (1232, 0.11631052629980884),
 (1251, 0.11631052629980884),
 (322, 0.1160517706371319),
 (966, 0.11534196721631888),
 (757, 0.11514154661795958),
 (1063, 0.11514154661795958),
 (171, 0.11514154661795957),
 (660, 0.11514154661795957),
 (385, 0.11396057645963795),
 (543, 0.11396057645963795),
 (1230, 0.11396057645963793),
 (593, 0.11295649894498098),
 (1128, 0.11295649894498098),
 (290, 0.11053942207134547),
 (706, 0.11053942207134546),
 (502, 0.11032175315897381),
 (785, 0.11009637651263607),
 (624, 0.11009637651263605),
 (764, 0.11009637651263605),
 (791, 0.10889310129609417),
 (1318, 0.1077284357109812),
 (63, 0.10754553500909855),
 (779, 0.1074430618700507),
 (1454, 0.1074430618700507),
 (475, 0.10713739108887085),
 (362, 0.10660035817780522),
 (1409, 0.10660035817780522),
 (1446, 0.10660035817780522),
 (1485, 0.10660035817780522),
 (238, 0.10555008273018725),
 (453, 0.10555008273018725),
 (1037, 0.10497277621629558),
 (1346, 0.10497277621629558),
 (1381, 0.10497277621629558),
 (109, 0.10444659357341869),
 (1433, 0.10403129732205987),
 (672, 0.10403129732205986),
 (1077, 0.10403129732205986),
 (1109, 0.10403129732205986),
 (103, 0.10403129732205985),
 (529, 0.1034175379990038),
 (1125, 0.10266540046786907),
 (1360, 0.10257624248277727),
 (936, 0.10241831129983783),
 (1412, 0.10241831129983783),
 (691, 0.1011805823145441),
 (1134, 0.1011805823145441),
 (976, 0.10050378152592121),
 (1185, 0.10050378152592121),
 (1069, 0.10050378152592118),
 (1482, 0.09984038297885897),
 (528, 0.09949366763261819),
 (750, 0.09869275424396536),
 (324, 0.09869275424396534),
 (464, 0.09869275424396534),
 (1016, 0.09869275424396534),
 (340, 0.09855206599818042),
 (1245, 0.09855206599818042),
 (977, 0.09847319278346618),
 (278, 0.09731236802019037),
 (439, 0.09731236802019037),
 (1453, 0.09731236802019037),
 (1344, 0.09656090991705352),
 (1488, 0.09656090991705352),
 (1442, 0.09534625892455922),
 (1430, 0.09496714704969829),
 (1091, 0.09475587393582685),
 (1201, 0.09456150270769184),
 (406, 0.09389050536260404),
 (690, 0.09385638197228471),
 (1118, 0.09385638197228471),
 (298, 0.09379580992210837),
 (369, 0.09304842103984708),
 (264, 0.09304842103984706),
 (864, 0.09278370237815067),
 (1263, 0.09278370237815067),
 (1110, 0.09237755128757118),
 (816, 0.09231861823449955),
 (927, 0.09231861823449955),
 (997, 0.09231861823449955),
 (801, 0.09231861823449954),
 (259, 0.09174698042719673),
 (970, 0.09143006417649888),
 (1143, 0.09143006417649888),
 (1476, 0.09143006417649888),
 (881, 0.0909090909090909),
 (1176, 0.0909090909090909),
 (938, 0.09074425108007847),
 (1187, 0.09074425108007847),
 (191, 0.08989331499509894),
 (1174, 0.08989331499509894),
 (1275, 0.08989331499509894),
 (1388, 0.08977369642581767),
 (1408, 0.08977369642581767),
 (462, 0.08977369642581766),
 (1459, 0.08956221510397981),
 (163, 0.08843153765707637),
 (756, 0.08843153765707637),
 (838, 0.08843153765707637),
 (1157, 0.08843153765707637),
 (1183, 0.08792249355666623),
 (1354, 0.08792249355666623),
 (650, 0.08764963426440373),
 (491, 0.08703882797784893),
 (1219, 0.08703882797784893),
 (1259, 0.08703882797784893),
 (544, 0.08703882797784891),
 (1282, 0.08703882797784891),
 (986, 0.0870388279778489),
 (853, 0.08618128166583652),
 (902, 0.08618128166583651),
 (498, 0.08570991287109667),
 (807, 0.08570991287109667),
 (844, 0.08570991287109667),
 (1003, 0.08570991287109667),
 (1082, 0.08570991287109667),
 (1356, 0.08570991287109667),
 (1403, 0.08570991287109667),
 (1203, 0.08534859274986487),
 (435, 0.08471737420873574),
 (573, 0.08471737420873574),
 (941, 0.08471737420873574),
 (1054, 0.08471737420873574),
 (1366, 0.08471737420873574),
 (793, 0.08453958309103057),
 (1064, 0.08453958309103057),
 (404, 0.0844400661841498),
 (1049, 0.0844400661841498),
 (1158, 0.0844400661841498),
 (889, 0.08375315127160099),
 (143, 0.08322503785764788),
 (219, 0.08322503785764788),
 (231, 0.08322503785764788),
 (924, 0.08322503785764788),
 (1084, 0.08322503785764788),
 (125, 0.08309324832467524),
 (640, 0.08309324832467524),
 (723, 0.08298826628866152),
 (283, 0.08257228238447704),
 (1053, 0.08257228238447704),
 (1288, 0.08257228238447704),
 (1420, 0.08257228238447704),
 (700, 0.08224396186997113),
 (1298, 0.08224396186997113),
 (431, 0.08206099398622181),
 (896, 0.08206099398622181),
 (1090, 0.08151933134075309),
 (554, 0.08151933134075308),
 (1464, 0.08094446585163528),
 (1154, 0.08081352297940449),
 (499, 0.08081352297940447),
 (637, 0.08081352297940447),
 (914, 0.08081352297940447),
 (619, 0.08058229640253803),
 (753, 0.08058229640253803),
 (856, 0.08058229640253803),
 (857, 0.08058229640253803),
 (897, 0.08058229640253803),
 (1025, 0.08058229640253803),
 (1029, 0.08058229640253803),
 (1135, 0.08058229640253803),
 (933, 0.07987230638308718),
 (1165, 0.07987230638308718),
 (1277, 0.07987230638308718),
 (1468, 0.07987230638308718),
 (122, 0.07945521577046602),
 (1193, 0.07945521577046602),
 (676, 0.07884165279854434),
 (701, 0.07884165279854434),
 (1133, 0.07884165279854434),
 (1197, 0.07884165279854434),
 (1393, 0.07884165279854434),
 (607, 0.07872958216222169),
 (763, 0.07872958216222169),
 (918, 0.07872958216222169),
 (703, 0.0781631749350903),
 (602, 0.0778498944161523),
 (981, 0.0778498944161523),
 (1122, 0.0778498944161523),
 (1458, 0.0778498944161523),
 (983, 0.07754035086653922),
 (300, 0.0769990503509018),
 (492, 0.0769990503509018),
 (999, 0.0769990503509018),
 (1027, 0.0769990503509018),
 (1066, 0.0769990503509018),
 (1326, 0.0769990503509018),
 (1419, 0.0769990503509018),
 (693, 0.07693218186208295),
 (921, 0.07693218186208295),
 (246, 0.07689464481087925),
 (587, 0.07689464481087925),
 (592, 0.07689464481087925),
 (1148, 0.07689464481087925),
 (1256, 0.07689464481087925),
 (954, 0.07689464481087924),
 (1311, 0.07633810206905742),
 (1253, 0.07537783614444092),
 (621, 0.07537783614444091),
 (783, 0.07537783614444091),
 (1302, 0.07537783614444091),
 (1399, 0.07537783614444091),
 (1462, 0.07537783614444091),
 (749, 0.07508510557782777),
 (930, 0.07508510557782777),
 (1286, 0.07508510557782777),
 (1404, 0.07508510557782777),
 (549, 0.07422696190252054),
 (1060, 0.07422696190252054),
 (1264, 0.07422696190252054),
 (576, 0.07385489458759964),
 (579, 0.07385489458759964),
 (1291, 0.07385489458759964),
 (207, 0.07339758434175737),
 (356, 0.07339758434175737),
 (556, 0.07339758434175737),
 (1007, 0.07339758434175737),
 (1240, 0.07277138997289952),
 (673, 0.07259540086406277),
 (708, 0.07259540086406277),
 (1402, 0.07259540086406277),
 (1439, 0.07259540086406277),
 (310, 0.07242068243779014),
 (705, 0.07242068243779014),
 (814, 0.07242068243779014),
 (1004, 0.07242068243779014),
 (1038, 0.07242068243779014),
 (1087, 0.07242068243779014),
 (428, 0.07181895714065413),
 (1023, 0.07181895714065413),
 (597, 0.0715454758790178),
 (888, 0.07106690545187015),
 (1352, 0.07106690545187015),
 (441, 0.07106690545187014),
 (1194, 0.07106690545187014),
 (1021, 0.07041787902195303),
 (384, 0.07033799484533299),
 (632, 0.07033799484533299),
 (1342, 0.07033799484533299),
 (915, 0.06988826808520128),
 (218, 0.06978631577988531),
 (308, 0.06978631577988531),
 (311, 0.06978631577988531),
 (1124, 0.06978631577988531),
 (1313, 0.06978631577988531),
 (1428, 0.06978631577988531),
 (1447, 0.06978631577988531),
 (477, 0.06963106238227913),
 (1141, 0.06963106238227913),
 (155, 0.0689450253326692),
 (1035, 0.0689450253326692),
 (1312, 0.06881023532039754),
 (217, 0.06857254813237415),
 (240, 0.06857254813237415),
 (282, 0.06857254813237415),
 (903, 0.06857254813237415),
 (1006, 0.06857254813237415),
 (1130, 0.06857254813237415),
 (1281, 0.06857254813237415),
 (1470, 0.06857254813237415),
 (1475, 0.06857254813237415),
 (196, 0.06827887419989188),
 (516, 0.06827887419989188),
 (817, 0.06827887419989188),
 (1467, 0.06796590597837959),
 (589, 0.06763166647282445),
 (767, 0.06763166647282445),
 (849, 0.06763166647282445),
 (1161, 0.0675552320918705),
 (643, 0.0674199862463242),
 (656, 0.0674199862463242),
 (751, 0.0674199862463242),
 (843, 0.0674199862463242),
 (871, 0.0674199862463242),
 (1444, 0.0674199862463242),
 (1484, 0.0674199862463242),
 (139, 0.0670025210172808),
 (432, 0.0670025210172808),
 (216, 0.06639061303092922),
 (339, 0.06632365324280728),
 (478, 0.06632365324280728),
 (638, 0.06632365324280728),
 (809, 0.06632365324280728),
 (828, 0.06632365324280728),
 (982, 0.06632365324280728),
 (1093, 0.06632365324280728),
 (249, 0.0657951694959769),
 (422, 0.0657951694959769),
 (446, 0.0657951694959769),
 (534, 0.0657951694959769),
 (1169, 0.0657951694959769),
 (1231, 0.0657951694959769),
 (1445, 0.0657951694959769),
 (22, 0.06560798513518473),
 (106, 0.06527912098338667),
 (618, 0.06527912098338667),
 (773, 0.06527912098338667),
 (944, 0.06527912098338667),
 (1211, 0.06527912098338667),
 (1287, 0.06527912098338667),
 (484, 0.06521546507260247),
 (212, 0.06487491201346024),
 (353, 0.06465081838352359),
 (430, 0.0642824346533225),
 (520, 0.0642824346533225),
 (916, 0.0642824346533225),
 (971, 0.0642824346533225),
 (1215, 0.0642824346533225),
 (559, 0.06410058864642093),
 (946, 0.06410058864642093),
 (1400, 0.06410058864642093),
 (215, 0.06356417261637282),
 (815, 0.06356417261637282),
 (1094, 0.06356417261637282),
 (1149, 0.06356417261637282),
 (1162, 0.06356417261637282),
 (1226, 0.06356417261637282),
 (1441, 0.06356417261637282),
 (1443, 0.06356417261637282),
 (1490, 0.06356417261637282),
 (50, 0.06333004963811235),
 (678, 0.06333004963811235),
 (854, 0.06333004963811235),
 (926, 0.06333004963811235),
 (990, 0.06333004963811235),
 (1243, 0.06333004963811235),
 (41, 0.06253053994807224),
 (397, 0.06253053994807224),
 (606, 0.06253053994807224),
 (644, 0.06253053994807224),
 (184, 0.06241877839323592),
 (417, 0.06241877839323591),
 (645, 0.06241877839323591),
 (905, 0.06241877839323591),
 (911, 0.06241877839323591),
 (973, 0.06241877839323591),
 (1147, 0.06241877839323591),
 (1222, 0.06241877839323591),
 (1364, 0.06241877839323591),
 (65, 0.06217059141274922),
 (390, 0.06203228069323138),
 (361, 0.06154574548966636),
 (504, 0.06154574548966636),
 (572, 0.06154574548966636),
 (836, 0.06154574548966636),
 (859, 0.06154574548966636),
 (1017, 0.06154574548966636),
 (1050, 0.06154574548966636),
 (1101, 0.06154574548966636),
 (1170, 0.06154574548966636),
 (1424, 0.06154574548966636),
 (94, 0.061545745489666355),
 (680, 0.06107048165524593),
 (718, 0.06107048165524593),
 (847, 0.06107048165524593),
 (157, 0.06070834938872646),
 (319, 0.06070834938872646),
 (641, 0.06070834938872646),
 (786, 0.06070834938872646),
 (1031, 0.06070834938872646),
 (1164, 0.06070834938872646),
 (1359, 0.06070834938872646),
 (479, 0.0606060606060606),
 (1172, 0.06015207623173694),
 (415, 0.05990422978731538),
 (808, 0.05990422978731538),
 (834, 0.05990422978731538),
 (917, 0.05990422978731538),
 (975, 0.05990422978731538),
 (1040, 0.05990422978731538),
 (1075, 0.05990422978731538),
 (1150, 0.05990422978731538),
 (1340, 0.05990422978731538),
 (1437, 0.05990422978731538),
 (702, 0.05970814340265321),
 (770, 0.05970814340265321),
 (858, 0.05970814340265321),
 (906, 0.05970814340265321),
 (1123, 0.05970814340265321),
 (1142, 0.05970814340265321),
 (1347, 0.05970814340265321),
 (1401, 0.05970814340265321),
 (32, 0.059273896596584934),
 (1450, 0.059273896596584934),
 (463, 0.05913123959890826),
 (496, 0.05913123959890826),
 (575, 0.05913123959890826),
 (608, 0.05913123959890826),
 (898, 0.05913123959890826),
 (1254, 0.05913123959890826),
 (1421, 0.05913123959890826),
 (483, 0.058433089509602486),
 (220, 0.05838742081211422),
 (540, 0.05838742081211422),
 (652, 0.05838742081211422),
 (679, 0.05838742081211422),
 (959, 0.05802588531856595),
 (1136, 0.05802588531856595),
 (1205, 0.05802588531856595),
 (1324, 0.05802588531856595),
 (1370, 0.05802588531856595),
 (1387, 0.05802588531856595),
 (1481, 0.05802588531856595),
 (197, 0.057670983608159435),
 (257, 0.057670983608159435),
 (688, 0.057670983608159435),
 (1111, 0.057670983608159435),
 (1216, 0.057670983608159435),
 (595, 0.05698028822981897),
 (725, 0.05698028822981897),
 (782, 0.05698028822981897),
 (957, 0.05698028822981897),
 (790, 0.05647824947249049),
 (865, 0.05647824947249049),
 (922, 0.05647824947249049),
 (984, 0.05647824947249049),
 (1028, 0.05647824947249049),
 (1294, 0.05647824947249049),
 (1349, 0.05647824947249049),
 (1371, 0.05647824947249049),
 (284, 0.05631382918337083),
 (1283, 0.05631382918337083),
 (1358, 0.05631382918337083),
 (1377, 0.05631382918337083),
 (546, 0.056110309077124325),
 (34, 0.055670221426890404),
 (92, 0.055670221426890404),
 (1045, 0.055670221426890404),
 (776, 0.055395498883116824),
 (230, 0.055048188256318034),
 (824, 0.055048188256318034),
 (910, 0.055048188256318034),
 (935, 0.055048188256318034),
 (1001, 0.055048188256318034),
 (141, 0.05504818825631803),
 (247, 0.05504818825631803),
 (269, 0.05504818825631803),
 (743, 0.05504818825631803),
 (950, 0.05504818825631803),
 (1002, 0.05504818825631803),
 (1252, 0.05504818825631803),
 (1407, 0.05504818825631803),
 (1413, 0.05504818825631803),
 (765, 0.054707329324147874),
 (739, 0.05444655064804708),
 (253, 0.054044185673496406),
 (162, 0.0538642178554906),
 (168, 0.0538642178554906),
 (423, 0.0538642178554906),
 (590, 0.0538642178554906),
 (772, 0.0538642178554906),
 (940, 0.0538642178554906),
 (1452, 0.0538642178554906),
 (295, 0.05372153093502535),
 (452, 0.05372153093502535),
 (732, 0.05372153093502535),
 (1119, 0.05372153093502535),
 (1199, 0.05372153093502535),
 (1208, 0.05372153093502535),
 (1258, 0.05372153093502535),
 (1382, 0.05372153093502535),
 (138, 0.053404586983455266),
 (192, 0.05330017908890261),
 (326, 0.05330017908890261),
 (1212, 0.05330017908890261),
 (1289, 0.05330017908890261),
 (36, 0.05275349613399974),
 (539, 0.05275349613399974),
 (761, 0.05275349613399974),
 (357, 0.05248638810814779),
 (418, 0.05248638810814779),
 (474, 0.05248638810814779),
 (493, 0.05248638810814779),
 (735, 0.05248638810814779),
 (963, 0.05248638810814779),
 (1026, 0.05248638810814779),
 (1030, 0.05248638810814779),
 (1146, 0.05248638810814779),
 (1152, 0.05248638810814779),
 (1190, 0.05248638810814779),
 (1191, 0.05248638810814779),
 (1300, 0.05248638810814779),
 (1429, 0.05248638810814779),
 (759, 0.05222329678670935),
 (1011, 0.05222329678670935),
 (1048, 0.05222329678670935),
 (144, 0.0517087689995019),
 (183, 0.0517087689995019),
 (547, 0.0517087689995019),
 (561, 0.0517087689995019),
 (603, 0.0517087689995019),
 (788, 0.0517087689995019),
 (450, 0.051613977409250916),
 (292, 0.05133270023393453),
 (671, 0.05133270023393453),
 (714, 0.05133270023393453),
 (762, 0.05133270023393453),
 (929, 0.05133270023393453),
 (1061, 0.05133270023393453),
 (1072, 0.05133270023393453),
 (1137, 0.05133270023393453),
 (1200, 0.05133270023393453),
 (1235, 0.05133270023393453),
 (1301, 0.05133270023393453),
 (87, 0.05120915564991892),
 (713, 0.05120915564991892),
 (879, 0.05120915564991892),
 (969, 0.05120915564991892),
 (972, 0.05120915564991892),
 (658, 0.05078367161190255),
 (1436, 0.05078367161190255),
 (344, 0.05072374985461834),
 (1105, 0.05072374985461834),
 (648, 0.050251890762960605),
 (748, 0.050251890762960605),
 (1217, 0.050251890762960605),
 (1220, 0.050251890762960605),
 (1363, 0.050251890762960605),
 (1374, 0.050251890762960605),
 (411, 0.0502518907629606),
 (611, 0.0502518907629606),
 (1435, 0.04999218933057798),
 (39, 0.049792959773196914),
 (792, 0.049792959773196914),
 (1415, 0.049792959773196914),
 (581, 0.04948464126834703),
 (412, 0.04934637712198267),
 (635, 0.04923659639173309),
 (662, 0.04923659639173309),
 (1472, 0.04923659639173309),
 (333, 0.04891159880445185),
 (429, 0.04891159880445185),
 (733, 0.04848811378764269),
 (1184, 0.04848811378764269),
 (1250, 0.04848811378764269),
 (79, 0.04828045495852676),
 (469, 0.04828045495852676),
 (488, 0.04828045495852676),
 (564, 0.04828045495852676),
 (651, 0.04828045495852676),
 (712, 0.04828045495852676),
 (727, 0.04828045495852676),
 (948, 0.04828045495852676),
 (1043, 0.04828045495852676),
 (1181, 0.04828045495852676),
 (1279, 0.04828045495852676),
 (1365, 0.04828045495852676),
 (95, 0.0480754414848157),
 (200, 0.0480754414848157),
 (351, 0.0480754414848157),
 (472, 0.0480754414848157),
 (487, 0.0480754414848157),
 (953, 0.0480754414848157),
 (1474, 0.0480754414848157),
 (444, 0.04767312946227961),
 (620, 0.04767312946227961),
 (863, 0.04737793696791343),
 (314, 0.047377936967913425),
 (517, 0.047377936967913425),
 (553, 0.047377936967913425),
 (629, 0.047377936967913425),
 (668, 0.047377936967913425),
 (669, 0.047377936967913425),
 (736, 0.047377936967913425),
 (795, 0.047377936967913425),
 (988, 0.047377936967913425),
 (1039, 0.047377936967913425),
 (1156, 0.047377936967913425),
 (1296, 0.047377936967913425),
 (345, 0.04728075135384592),
 (675, 0.04728075135384592),
 (931, 0.046733309148852105),
 (60, 0.04652421051992354),
 (108, 0.04652421051992354),
 (153, 0.04652421051992354),
 (387, 0.04652421051992354),
 (480, 0.04652421051992354),
 (895, 0.04652421051992354),
 (1036, 0.04652421051992354),
 (1139, 0.04652421051992354),
 (1345, 0.04652421051992354),
 (1417, 0.04652421051992354),
 (1471, 0.04652421051992354),
 (769, 0.04652421051992353),
 (199, 0.046159309117249775),
 (85, 0.04580286124143445),
 (1372, 0.04580286124143445),
 (489, 0.04571503208824944),
 (802, 0.04571503208824944),
 (813, 0.04571503208824944),
 (908, 0.04571503208824944),
 (964, 0.04571503208824944),
 (998, 0.04571503208824944),
 (1268, 0.04571503208824944),
 (666, 0.04545454545454545),
 (787, 0.04545454545454545),
 (1337, 0.04545454545454545),
 (154, 0.04511405717380271),
 (248, 0.04494665749754947),
 (262, 0.04494665749754947),
 (382, 0.04494665749754947),
 (594, 0.04494665749754947),
 (775, 0.04494665749754947),
 (810, 0.04494665749754947),
 (1196, 0.04494665749754947),
 (1234, 0.04494665749754947),
 (323, 0.044781107551989906),
 (299, 0.044215768828538185),
 (309, 0.044215768828538185),
 (359, 0.044215768828538185),
 (548, 0.044215768828538185),
 (623, 0.044215768828538185),
 (636, 0.044215768828538185),
 (869, 0.044215768828538185),
 (1247, 0.044215768828538185),
 (1392, 0.044215768828538185),
 (885, 0.044136741475237475),
 (206, 0.04382481713220186),
 (1138, 0.04382481713220186),
 (1218, 0.04382481713220186),
 (19, 0.04351941398892445),
 (71, 0.04351941398892445),
 (119, 0.04351941398892445),
 (320, 0.04351941398892445),
 (485, 0.04351941398892445),

In [52]:
def recommend(movie):
    index=new[new['title']==movie].index[0]
    distances=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x:x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [53]:
recommend('The Lego Movie')

Fantasia
Standing Ovation
Raise Your Voice
Bandslam
I'm Not There.

In [54]:
import pickle

In [57]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [58]:
pip show pandas

Name: pandas
Version: 1.5.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: c:\users\user\anaconda3\lib\site-packages
Requires: numpy, python-dateutil, pytz
Required-by: datashader, holoviews, hvplot, seaborn, statsmodels, xarray
Note: you may need to restart the kernel to use updated packages.